name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 4.4.0
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.3.2"

dependencies:
  circle_flags: ^5.0.0
  dart_countries: ^3.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  phone_numbers_parser: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
